#pragma once

enum MotionState{	//live status
	IDLE = 0,
	DEAD = 1,

	//attack related status
	ATTACK = 2,
	HEAVY_ATTACK = ATTACK << 1,
	DAMAGED = HEAVY_ATTACK << 1,
	COOL_DOWN = DAMAGED << 1,
	BOOST =  COOL_DOWN << 1,

	//moving  start from 256
	MOVE_FORWARD = 1 << 9,
	MOVE_BACKWARD = MOVE_FORWARD << 1,
	MOVE_LEFT = MOVE_BACKWARD << 1,
	MOVE_RIGHT = MOVE_LEFT << 1,
	TURN_LEFT = MOVE_RIGHT << 1,
	TURN_RIGHT = TURN_LEFT << 1,
	JUMP = TURN_RIGHT << 1,
	MOVE_LEFT_FORWARD = MOVE_LEFT + MOVE_FORWARD,
	MOVE_LEFT_BACKWARD = MOVE_LEFT + MOVE_BACKWARD,
	MOVE_RIGHT_FORWARD = MOVE_RIGHT + MOVE_FORWARD,
	MOVE_RIGHT_BACKWARD = MOVE_RIGHT + MOVE_BACKWARD
};